### ISSUE TITLE
Annotation error

### ISSUE THREAD

**Issue by JonathonLuiten** [lvis-dataset/lvis-api#1]
Hey. We found a few issues with the annotations of the VAL set. 

For this image: 
Image ID: 19924
![image](https://user-images.githubusercontent.com/23000532/64115457-9d02db80-cd87-11e9-8090-075f1dbe4747.png)
Which can be found on 'explore' by looking up 'necktie' and 'hat'.

And also for this image:
Image ID: 338304
![image](https://user-images.githubusercontent.com/23000532/64115797-6f6a6200-cd88-11e9-9431-b9e92cbeaeeb.png)
Which can be found on 'explore' by looking up 'sheep' and 'hat'.

It appears that these annotations are rotated. 

We are looking to use this dataset now and are concerned that other images, e.g. from the training set, could have the same problem. Is there some assurance that could be given that this is not a problem for the rest of the images? 

Thanks a lot for making this dataset. It is super useful.

Regards,
Jonathon Luiten

**Comment by agrimgupta92** [comment]
Thanks for reporting the annotations errors. For some background we did collect annotations on coco images but they might have differed by some angle [90, 270, 180]. We have corrected all of these rotation errors but a very small number might still persist like the ones you shared. We will fix images you reported in v1 release of the dataset. 

In future please share errors/issues related to the dataset in the google group lvis-dataset@googlegroups.com. This repo is for discussions/issues regarding lvis-api.
