### ISSUE TITLE
Error In Matplotlib while installing

### ISSUE THREAD

**Issue by onexmaster** [lvis-dataset/lvis-api#14]
Tried installing lvis api, but getting this error
`
ERROR: Could not find a version that satisfies the requirement matplotlib==3.1.1 (from lvis) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1
, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3)
ERROR: No matching distribution found for matplotlib==3.1.1 (from lvis)
`

**Comment by dragonnikkirocks** [comment]
how did you solve this?
