### ISSUE TITLE
How to get the dataset by api?

### ISSUE THREAD

**Issue by curryJ** [lvis-dataset/lvis-api#17]
## ❓ Questions and Help
Thanks for offering this api.
I can't open the website https://www.lvisdataset.org/,so I want to ask you how to get the dataset by this api or the instruction of this api.
Thank you !!!

**Comment by agrimgupta92** [comment]
The correct website link is: https://www.lvisdataset.org
You can't download the dataset via the API. You can download the dataset here: https://www.lvisdataset.org/dataset
Example usage for evaluation can be found here: https://github.com/lvis-dataset/lvis-api/blob/master/test.py
