### ISSUE TITLE
A confusion on _get_gt_dt function

### ISSUE THREAD

**Issue by laoreja** [lvis-dataset/lvis-api#18]
Thanks for the clean code!
I have a confusion about the `_get_gt_dt` function,

in line https://github.com/lvis-dataset/lvis-api/blob/031ac21f939bcb5f1ca8de2ab8704082e101ff9b/lvis/eval.py#L158 and https://github.com/lvis-dataset/lvis-api/blob/031ac21f939bcb5f1ca8de2ab8704082e101ff9b/lvis/eval.py#L163, according to the doc string of the function that parameter `cat_id` is not used, should the `cat_id` be `_cat_id` actually?

i.e., `for _ann in self._gts[img_id, _cat_id]`? 

Anyway, the default value of `use_cats` is set to 1, so this piece of code is not used in evaluation.

**Comment by rbgirshick** [comment]
Fixed by #36.

One note: due to the federated label structure, category agnostic evaluation does not make sense in LVIS for *precision*. It is sensible for calculating recall.
