### ISSUE TITLE
The class 'hot-dog' in coco_to_synset.json

### ISSUE THREAD

**Issue by Yinyf0804** [lvis-dataset/lvis-api#29]
## ❓ Questions and Help
The class 'hot-dog' in coco is desribed in coco_to_synset.json as follows:
"hot dog": {"coco_cat_id": 58, "meaning": "a smooth-textured sausage, usually smoked, often served on a bread roll", "synset": "frank.n.02"}, 
but there is no "frank.n.02" in lvis classes. What's the corresponding class for "hot-dog" in lvis?

Thanks!

**Comment by rbgirshick** [comment]
It seems that LVIS does not have a good equivalent to this COCO category. We may have had `frank.n.02` in early prototypes of the dataset, but rejected it due to bellow-bar annotation quality.

**Comment by Yinyf0804** [comment]
Thanks for your advice!
