### ISSUE TITLE
how to join lvis-dataset@googlegroups.com

### ISSUE THREAD

**Issue by twangnh** [lvis-dataset/lvis-api#4]
Really hope you can help on this, I can't find the group of lvis-dataset@googlegroups.com on google groups? should we just send emails to this address?

**Comment by agrimgupta92** [comment]
We have fixed the setting. You should now be able to search for lvis-dataset in google groups.

**Comment by rbgirshick** [comment]
For reference, it is [here](https://groups.google.com/forum/#!forum/lvis-dataset).
