### ISSUE TITLE
V1.0 val set only has 5K images

### ISSUE THREAD

**Issue by WangYZ1608** [lvis-dataset/lvis-api#43]
## ❓ Questions and Help
The [LVIS website](https://www.lvisdataset.org/dataset) points that the validation set has 20k images, but when I downloaded it, there were only 5k images. 

Where can I download the 20k validation set? Can you give me a link？

**Comment by evantkchong** [comment]
Encountered the same issue when downloading and unzipping `val2017.zip` from the [dataset download page](https://www.lvisdataset.org/dataset)

**Comment by rbgirshick** [comment]
It's a bit confusing: the LVIS val set uses images from both COCO train and COCO val.

> LVIS val set contains images from COCO 2017 train in addition to the COCO 2017 val split

You need to download both train2017.zip and val2017.zip in order to get all ~20k images that are used in LVIS val.

**Comment by evantkchong** [comment]
Thanks for the response @rbgirshick! Typically would one store all images for lvis in the same directory instead of separate `train`, `val` and `test` directories?

**Comment by WangYZ1608** [comment]
> It's a bit confusing: the LVIS val set uses images from both COCO train and COCO val.
> 
> > LVIS val set contains images from COCO 2017 train in addition to the COCO 2017 val split
> 
> You need to download both train2017.zip and val2017.zip in order to get all ~20k images that are used in LVIS val.

Thanks. I see.
