### ISSUE TITLE
AP inconsistency

### ISSUE THREAD

**Issue by tztztztztz** [lvis-dataset/lvis-api#8]
## ❓ Questions and Help

The results of eval.AI is inconsistent with results  of lvis api. Do you use different evalution code on eval.AI?

**Comment by rbgirshick** [comment]
We're following up privately on email to get specific information. Will update here with our findings.

**Comment by rbgirshick** [comment]
[Confirmed in the Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lvis-dataset/3g9smqH4CEc/iY_H2ZqmBAAJ) that the inconsistency was due to using code from before the bug fix in 73142a45d38f77da13426a952c9b12e2dc256484.
